from typing_extensions import TypedDict
from typing import List

### Our graph state
class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        emails: List of email dictionaries containing details of new emails.
        viewed_emails_ids: List of email IDs that have been viewed.
        ready_emails: List of emails that are ready to be sent.
        email_sender: Email address of the sender of the current email.
        email_category: Category of the current email (e.g., product enquiry, customer feedback).
        email_subject: Subject of the generated email draft.
        generated_email: Content of the email generated by the write agent.
        rag_questions: List of questions designed for Retrieval-Augmented Generation (RAG).
        retrieved_infos: Information retrieved from RAG to answer enquiry.
        review: Review result of the generated email (send or rewrite).
        trials: Number of draft trials attempted before stopping.
    """
    emails: List[dict]
    viewed_emails_ids: List[str]
    ready_emails: List[dict]
    email_sender: str
    email_category: str
    email_subject: str
    generated_email: str
    rag_questions: List[str]
    retrieved_infos: str
    review: str
    trials: int
